#!/bin/bash 

USER_FILE=ssusers

create_json () {
    echo '{' >JSON_FILE.tmp
    sed -E 's/(.*)/    \1/' ssmlt.template >> JSON_FILE.tmp 
    awk '
    BEGIN {
        FS=",";
        i=1;
        printf("      \"port_password\": {\n");
    }
    ! /^#|^\s*$/ {
        port=$1;
        pw=$2;
        ports[i++] = port;
        pass[port]=pw;
    }
    END {
        for(j=1;j<i;j++) {
            port=ports[j];
            printf("        \"%s\": \"%s\"", port, pass[port]);
            if(j<i-1) printf(",");
            printf("\n");
        }
        printf("    }\n");
    }
    ' $USER_FILE >> JSON_FILE.tmp
    echo '}' >> JSON_FILE.tmp
    mv JSON_FILE.tmp JSON_FILE

}

create_json
